[package]
name = "teststrings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9.22"
scraper = "0.11.0"
tokio = { version = "1", features = ["full"] }
mini-redis = "0.4"
